name: 'prototype'
# data parameters
dataset_name: celeba
data_with_subfolder: False
train_data_path: /home/pikey/DataSet/celeba
val_data_path:
resume: /home/pikey/Data/II/baseline/baseline/celeba/hole_benchmark/
batch_size: 1
image_shape: [256, 256, 3]
mask_shape: [128, 128]
mask_batch_same: True
max_delta_shape: [32, 32]
margin: [0, 0]
discounted_mask: True
spatial_discounting_gamma: 0.9
random_crop: True
mask_type: hole     # hole | mosaic
mosaic_unit_size: 12

# training parameters
expname: benchmark
cuda: True
gpu_ids: [0,1]    # set the GPU ids to use, e.g. [0] or [1, 2]
num_workers: 4
lr: 0.0001
beta1: 0.5
beta2: 0.9
train_generator_interval: 5
niter: 500000
print_iter: 100

# log parameters
save_dir: '/data2/pikey/Data/II'
# loss weight
coarse_l1_alpha: 1.2
l1_loss_alpha: 1.2
ae_loss_alpha: 1.2
global_wgan_loss_alpha: 1.
gan_loss_alpha: 0.001
wgan_gp_lambda: 10

#ddpg config
ssim_window_size: 8

# network parameters
input_dim: 3
coarse_gen_num: 3
netG:
  input_dim: 3
  ngf: 32
  coarse_gen_num: 3 #must be same as coarse_gen_num before
netD:
  input_dim: 3
  ndf: 64



